import os
import re
import time
import json
import subprocess
 
# --- 1. DYNAMIC CONFIGURATION ---
GOLD_JSON = "gold_netlist.json"
FAULT_DIR = "faults"
LOG_DIR = "logs"
SOLVER_LOG_DIR = os.path.join(LOG_DIR, "solver_details")
 
os.makedirs(LOG_DIR, exist_ok=True)
os.makedirs(SOLVER_LOG_DIR, exist_ok=True)
 
# Read the gold netlist for metadata
with open(GOLD_JSON, "r") as f:
    gold_data = json.load(f)
 
module_name = list(gold_data["modules"].keys())[0]
module_data = gold_data["modules"][module_name]
 
input_ports = sorted([
    name for name, info in module_data.get("ports", {}).items()
    if info.get("direction") == "input"
])
 
print(f"Detected Module: {module_name}")
print(f"Tracking {len(input_ports)} input ports for test vectors.")
 
# --- 2. FAULT PROCESSING ---
results = []
files = sorted([f for f in os.listdir(FAULT_DIR) if f.endswith(".json")])
 
for file in files:
    cnf_file = os.path.join(FAULT_DIR, f"{file}.cnf")
    yosys_log = os.path.join(LOG_DIR, f"{file}.yosys.log")
    solver_log = os.path.join(SOLVER_LOG_DIR, f"{file}.solver.txt")
 
    # Step A: Run Yosys to generate CNF and check logic
    # yosys_script = f"""
    # design -reset
    # read_json {GOLD_JSON}
    # rename {module_name} gold_model
    # design -stash gold
    
    # design -reset
    # read_json {FAULT_DIR}/{file}
    # rename {module_name} faulty_model
    # design -stash fault
    
    # design -copy-from gold gold_model
    # design -copy-from fault faulty_model
    # read_liberty -ignore_miss_func NangateOpenCellLibrary_typical.lib
    # miter -equiv -make_outputs -make_outcmp gold_model faulty_model miter
    # hierarchy -top miter
    # flatten
    # opt
    
    # # We dump the CNF for the external solver
    # sat -dump_cnf {cnf_file} -show-ports -set trigger 1 miter
    # """

    yosys_script = f"""
    design -reset
    read_liberty -ignore_miss_func NangateOpenCellLibrary_typical.lib
    read_json {GOLD_JSON}
    rename {module_name} gold_model
    design -stash gold

    design -reset
    read_liberty -ignore_miss_func NangateOpenCellLibrary_typical.lib
    read_json {FAULT_DIR}/{file}
    rename {module_name} faulty_model
    design -stash fault

    design -reset
    read_liberty -ignore_miss_func NangateOpenCellLibrary_typical.lib
    design -copy-from gold gold_model
    design -copy-from fault faulty_model

    miter -equiv -make_outcmp gold_model faulty_model miter
    hierarchy -top miter
    flatten
    abc -g gates
    opt_clean

    sat -dump_cnf {cnf_file} -show-ports -show-inputs -set trigger 1 miter
"""
 
    with open("temp.ys", "w") as f:
        f.write(yosys_script)
 
    os.system(f"yosys temp.ys > {yosys_log} 2>&1")
 
    # Step B: Run External Solver (MiniSat) for deep stats
    # -verb=2 gives high verbosity for heuristics/conflict stats
    start_time = time.perf_counter()
    # We use MiniSat to solve the CNF generated by Yosys
    subprocess.run(f"minisat -verb=2 {cnf_file} > {solver_log} 2>&1", shell=True)
    duration = time.perf_counter() - start_time
 
    # --- 3. PARSE RESULTS ---
    with open(yosys_log) as f:
        y_log = f.read()
    with open(solver_log) as f:
        s_log = f.read()

    if "UNSATISFIABLE" in s_log:
        status = "UNSAT"
    elif "SATISFIABLE" in s_log:
        status = "DETECTED"
    else:
        status = "ERROR"
 
    # Deep Stats Extraction using Regex
    def get_stat(pattern, text, default="0"):
        match = re.search(pattern, text)
        return match.group(1) if match else default
 
    deep_stats = {
        "restarts":     get_stat(r"restarts\s+:\s+(\d+)", s_log),
        "conflicts":    get_stat(r"conflicts\s+:\s+(\d+)", s_log),
        "decisions":    get_stat(r"decisions\s+:\s+(\d+)", s_log),
        "propagations": get_stat(r"propagations\s+:\s+(\d+)", s_log),
        "conflict_lits":get_stat(r"conflict literals\s+:\s+(\d+)", s_log),
        "mem_mb":       get_stat(r"Memory used\s+:\s+([\d\.]+)", s_log),
        "cpu_time":     get_stat(r"CPU time\s+:\s+([\d\.]+)", s_log)
    }
 
    # Extract test vector from Yosys log
    def extract_values(log, ports):
        values = {p: "-" for p in ports}
        for line in log.splitlines():
            line = line.strip()
            for p in ports:
                for key in [f"\\{p}", f"\\in_{p}"]:
                    if line.startswith(key):
                        parts = line.split()
                        if len(parts) >= 2: values[p] = parts[-1]
        return values
 
    vals = extract_values(y_log, input_ports)
    
    # Construct row: [metadata] + [deep stats] + [test vector]
    row = [file, status, f"{duration:.4f}"] + list(deep_stats.values()) + [vals[p] for p in input_ports]
    results.append(row)
 
# --- 4. SAVE COMPLETE CSV ---
with open("original_results.csv", "w") as f:
    stat_headers = ["restarts", "conflicts", "decisions", "props", "conf_lits", "mem_mb", "solver_time"]
    header = ["fault", "status", "total_time_sec"] + stat_headers + input_ports
    f.write(",".join(header) + "\n")
    for r in results:
        f.write(",".join(map(str, r)) + "\n")
 
print(f"Done. Processed {len(results)} faults with full SAT metrics.")